#!/bin/bash
# ==============================================================================
# Rollback Script
# ==============================================================================
# Generated by executor.sh
# This script can be executed manually if automatic rollback fails
# ==============================================================================

set -euo pipefail

# Operation: Install Google Chrome Enterprise
# Execution ID: app-chrome_20251207_034618_c5TO
# Generated: Sun Dec  7 03:46:19 UTC 2025

# Step: Uninstall Chrome
echo '[*] Executing: Uninstall Chrome'
$app = Get-WmiObject Win32_Product | Where-Object { $_.Name -like "*Chrome*" }
if ($app) { $app.Uninstall() }

echo '[v] Rollback completed'
