#!/bin/bash
# ==============================================================================
# Rollback Script
# ==============================================================================
# Generated by executor.sh
# This script can be executed manually if automatic rollback fails
# ==============================================================================

set -euo pipefail

# Operation: Create Dynamic Entra ID Device Group
# Execution ID: dynamic-device-group-create_20251208_053340_rcJb
# Generated: Mon Dec  8 05:33:42 UTC 2025

# Step: Delete Device Group
echo '[*] Executing: Delete Device Group'
az ad group delete \
  --group "{{group_name}}" \
  --yes

echo '[v] Rollback completed'
