#!/bin/bash
# ==============================================================================
# Rollback Script
# ==============================================================================
# Generated by executor.sh
# This script can be executed manually if automatic rollback fails
# ==============================================================================

set -euo pipefail

# Operation: Create AVD Session Host VM
# Execution ID: session-host-create_20251208_041059_aIit
# Generated: Mon Dec  8 04:11:02 UTC 2025

# Step: Delete Session Host VM
echo '[*] Executing: Delete Session Host VM'
az vm delete \
  --resource-group "RG-Azure-VDI-01" \
  --name "{{SESSION_HOST_VM_NAME}}" \
  --force-deletion yes \
  --yes

echo '[v] Rollback completed'
