#!/bin/bash
# ==============================================================================
# Rollback Script
# ==============================================================================
# Generated by executor.sh
# This script can be executed manually if automatic rollback fails
# ==============================================================================

set -euo pipefail

# Operation: Test Rollback Generation
# Execution ID: test_rollback_gen_1765340695_ABC1
# Generated: Wed Dec 10 04:24:55 UTC 2025

# Step: Cleanup
echo '[*] Executing: Cleanup'
echo Cleanup complete

# Step: Delete VNet
echo '[*] Executing: Delete VNet'
az network vnet delete --resource-group rg-test-01 --name vnet-test --yes

echo '[v] Rollback completed'
