#!/bin/bash
# ==============================================================================
# Rollback Script
# ==============================================================================
# Generated by executor.sh
# This script can be executed manually if automatic rollback fails
# ==============================================================================

set -euo pipefail

# Operation: Test Rollback Execution
# Execution ID: test-rollback-exec_20251206_184215_k2TN
# Generated: Sat Dec  6 18:42:15 UTC 2025

# Step: Remove marker
echo '[*] Executing: Remove marker'
rm -f /mnt/cache_pool/development/azure-cli/tests/test-data/executor/marker.txt

echo '[v] Rollback completed'
